name: .NET Core

on:
  push:
    branches: [ develop, feature/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - 
            name : Checkout
            uses: actions/checkout@v2
            with:
                fetch-depth: 0
        - 
            name: Setup .NET Core
            uses: actions/setup-dotnet@v1
            with:
                dotnet-version: 6.0.x
        - 
            name: MyComicsManagerApi Install dependencies
            run: dotnet restore "./MyComicsManagerApi.csproj"
        - 
            name: MyComicsManagerApi Build
            run: dotnet build "./MyComicsManagerApi.csproj" --configuration Release --no-restore
        - 
            name: MyComicsManagerApi.Tests Install dependencies
            run: dotnet restore ".\MyComicsManagerApi.Tests\MyComicsManagerApiTests.csproj"
        - 
            name: MyComicsManagerApi Test
            run: dotnet test ".\MyComicsManagerApi.Tests\MyComicsManagerApiTests.csproj" --no-restore --verbosity normal